'_FULLSCREEN
_TITLE "Alarm Clock 4 Directions"
DIM ROWS(4, 30) AS STRING
DIM GIMME_PATH AS STRING

FOR DIRECTION_INDEX = 1 TO 4
    GIMME_PATH = "data/" + STR$(DIRECTION_INDEX) + ".asc"
    PRINT GIMME_PATH
    LINE_COUNTER = 1
    OPEN GIMME_PATH FOR INPUT AS #1
    DO UNTIL EOF(1)
        INPUT #1, ROWS(DIRECTION_INDEX, LINE_COUNTER)
        LINE_COUNTER = LINE_COUNTER + 1
    LOOP
    CLOSE #1
NEXT DIRECTION_INDEX

FOR i = 1 TO 30
    PRINT ROWS(1, i)
NEXT i
