_FULLSCREEN
_TITLE "Alarm Clock 4 Directions"
DIM ROWS(4, 30) AS STRING
DIM GIMME_PATH AS STRING

DIM GIMME_CHAR AS STRING
DIM GIMME_LINE AS STRING

FOR DIRECTION_INDEX = 1 TO 4
    GIMME_PATH = "data/chr/" + CHR$(DIRECTION_INDEX + 48) + ".chr"
    LINE_COUNTER = 0
    CHAR_COUNTER = 1
    IF DIRECTION_INDEX MOD 2 = 0 THEN ROW_PER_ASC = 5 ELSE ROW_PER_ASC = 4
    OPEN GIMME_PATH FOR INPUT AS #1
    DO UNTIL EOF(1)
        INPUT #1, GIMME_CHAR
        GIMME_LINE = GIMME_LINE + CHR$(VAL(GIMME_CHAR))
        IF CHAR_COUNTER MOD ROW_PER_ASC = 0 THEN
            LINE_COUNTER = LINE_COUNTER + 1
            ROWS(DIRECTION_INDEX, LINE_COUNTER) = GIMME_LINE
            GIMME_LINE = ""
        END IF
        CHAR_COUNTER = CHAR_COUNTER + 1
    LOOP
    CLOSE #1
NEXT DIRECTION_INDEX

FOR i = 1 TO 30
    PRINT ROWS(1, i) + "                " + ROWS(2, i) + "              " + ROWS(3, i) + "              " + ROWS(4, i)
NEXT i
